// All figures are verified from official sources unless verified: false.
// Costs and requirements change yearly — always link users to sourceUrl before they apply.

export const UNIVERSITIES = [
  {
    id: 'tum',
    name: 'Technical University of Munich (TUM)',
    country: 'Germany',
    city: 'Munich',
    flag: '🇩🇪',
    ranking: '#22 QS World 2026 · #1 in Germany',
    knownFor: ['Engineering', 'Computer Science', 'Natural Sciences', 'Management'],
    language: "Mostly German at bachelor's level; limited English-taught options (e.g. Management & Technology, Information Engineering)",
    entryGrades: "~75% / German GPA 2.0 minimum for bachelor's; competitive programmes expect higher",
    tests: 'English programmes: IELTS 6.5+ or TOEFL iBT 88+. German programmes: German B2/C1 (TestDaF 4×4 or DSH-2)',
    acceptance: 'Highly competitive — ~8% acceptance',
    tuitionIntl: "€2,000–€3,000/semester for non-EU bachelor's (~$4,300–$6,500/yr) — new since 2024; waivers available",
    living: 'Munich is pricey — budget ~€11,208/yr',
    deadline: '~July 15 for winter intake (undergrad)',
    scholarshipsHere: 'Merit & need-based tuition waivers can cover the new fees',
    scholarships: [
      {
        name: 'TUM Merit & Need-based Tuition Waiver',
        percentage: 'Up to 100% of tuition fees',
        whoQualifies: 'Top-performing admitted students; need-based options available',
        howToApply: 'Apply via TUM after admission; deadline ~May 31',
        deadlineMonth: 5,
        amountTier: 1,
        level: 'Undergraduate',
        verified: true,
      },
    ],
    sourceName: 'TUM (official)',
    sourceUrl: 'https://www.tum.de/en/studies',
    verified: true,
  },
  {
    id: 'uct',
    name: 'University of Cape Town (UCT)',
    country: 'South Africa',
    city: 'Cape Town',
    flag: '🇿🇦',
    ranking: '#1 in Africa · Top 200 globally',
    knownFor: ['Health Sciences', 'Commerce', 'Engineering', 'Humanities', 'Science'],
    language: 'English-medium instruction',
    entryGrades: 'Varies by faculty — based on your final school results (e.g. NSC / A-Levels); competitive faculties like Health Sciences and Commerce expect high marks. Confirm the points requirement for your programme.',
    tests: 'IELTS 6.5 or TOEFL iBT 88 (English-taught)',
    acceptance: 'Competitive — varies significantly by faculty',
    tuitionIntl: "International undergraduate ~R121,700/yr (~$6,600 USD) + R5,600 international service fee; Master's (coursework) ~R81,000/yr (~$4,400 USD). Verified 2026 — fees vary by faculty/course; confirm on the official site.",
    living: 'Cape Town is more affordable than most Western cities — budget for rent, food and transport. Living costs are a general estimate; confirm current figures.',
    deadline: 'Key dates for 2026: initial payment by 6 Feb 2026, balance by 31 July 2026',
    scholarshipsHere: "UCT offers some international merit and faculty scholarships, and the Mandela Rhodes Scholarship is tenable here for postgraduate (Honours / Master's) study. Check UCT's international office for current options.",
    scholarships: [],
    sourceName: 'University of Cape Town (official)',
    sourceUrl: 'https://uct.ac.za/international',
    verified: true,
  },
  {
    id: 'stellenbosch',
    name: 'Stellenbosch University',
    country: 'South Africa',
    city: 'Stellenbosch',
    flag: '🇿🇦',
    ranking: 'Top 300 · QS & Times Higher Education',
    knownFor: ['Engineering', 'Business', 'AgriSciences', 'Medicine & Health', 'Science'],
    language: 'English and Afrikaans — many programmes available in English; confirm the language of your specific programme.',
    entryGrades: 'Varies by faculty — based on your final school results; confirm the admission requirements for your chosen programme.',
    tests: 'IELTS / TOEFL proof of English proficiency required',
    acceptance: 'Competitive — varies by faculty',
    tuitionIntl: 'International undergraduate roughly $2,300–$4,500/yr (varies by faculty), plus international registration & tuition fees. International application fee: R400 (non-refundable). Verified 2026 — fees vary by faculty; confirm on the official site.',
    living: 'Stellenbosch (near Cape Town) is more affordable than most Western cities — budget for rent, food and transport. Living costs are a general estimate; confirm current figures.',
    deadline: 'Undergraduate applications close 31 July (for the following year); offers released from mid-January',
    scholarshipsHere: "Stellenbosch offers some international and faculty merit awards, and the Mandela Rhodes Scholarship is tenable here for postgraduate (Honours / Master's) study. Check the university's international office for current options.",
    scholarships: [],
    sourceName: 'Stellenbosch University (official)',
    sourceUrl: 'https://www.su.ac.za/en/apply',
    verified: true,
  },
  {
    id: 'auc',
    name: 'The American University in Cairo (AUC)',
    country: 'Egypt',
    city: 'Cairo',
    flag: '🇪🇬',
    ranking: 'US-accredited private university · English-medium',
    knownFor: ['Business', 'Engineering', 'Computer Science', 'Political Science', 'Humanities'],
    language: 'English-medium instruction',
    entryGrades: 'Selective; requirements vary by school/programme — confirm on the official site.',
    tests: 'TOEFL / IELTS / Duolingo required (English placement is based on your highest score). Confirm current minimums on the official site.',
    acceptance: 'Selective — varies by programme',
    tuitionIntl: 'Undergraduate ~$735 per credit hour for international students (verified 2026, aucegypt.edu), paid in USD. A full-time load of ~30 credits/year works out to roughly ~$22,000/yr — confirm your credit load, as the official page states the per-credit rate, not an annual total.',
    living: 'Cairo living costs are low by international standards — a rough estimate; confirm current figures.',
    deadline: 'Fall and spring intakes only (fall runs in early and final cycles). Confirm exact dates on the official site.',
    scholarshipsHere: 'AUC Excellence Scholarships — stackable merit awards covering up to 100% of tuition for high-achieving students; various faculty and need-based aid also available.',
    scholarships: [
      {
        name: 'AUC Excellence Scholarships',
        percentage: 'Up to 100% of tuition',
        whoQualifies: 'High-achieving admitted undergraduates (competitive, stackable awards)',
        howToApply: 'Considered on admission; confirm the current deadline on aucegypt.edu',
        amountTier: 1,
        level: 'Undergraduate',
        verified: true,
      },
    ],
    sourceName: 'The American University in Cairo (official)',
    sourceUrl: 'https://www.aucegypt.edu/admissions/tuition-and-financial-assistance',
    verified: true,
  },
  {
    id: 'bue',
    name: 'The British University in Egypt (BUE)',
    country: 'Egypt',
    city: 'Cairo',
    flag: '🇪🇬',
    ranking: 'UK-validated degrees · English-medium',
    knownFor: ['Engineering', 'Business', 'Computer Science', 'Pharmacy', 'Law'],
    language: 'English-medium instruction',
    entryGrades: 'Competitive, with priority to higher scores — confirm requirements per programme on the official site.',
    tests: 'IELTS / TOEFL or the BUE English placement test required — confirm the required level on the official site.',
    acceptance: 'Competitive — priority given to higher scores',
    tuitionIntl: 'International undergraduate tuition (2025-2026, verified) ranges roughly £2,900–£12,000/yr by programme (~$3,700–$15,200 USD) — e.g. Law/Economics from £6,900, Engineering up to £10,500, Dentistry up to £11,970. Paid in GBP or USD equivalent. Fees vary by faculty; confirm on the official site.',
    living: 'Cairo living costs are low by international standards — a rough estimate; confirm current figures.',
    deadline: 'Confirm application deadlines on the official admissions site.',
    scholarshipsHere: 'BUE offers merit and need-based scholarships for high-achieving students — confirm current awards on the official site.',
    scholarships: [],
    sourceName: 'The British University in Egypt (official)',
    sourceUrl: 'https://www.bue.edu.eg/tuition-fees-international-2025',
    verified: true,
  },
  {
    id: 'guc',
    name: 'The German University in Cairo (GUC)',
    country: 'Egypt',
    city: 'Cairo',
    flag: '🇪🇬',
    ranking: 'German-model private university · English-medium',
    knownFor: ['Engineering', 'Pharmacy', 'Management', 'Biotechnology', 'Dentistry'],
    language: 'Primarily English-medium, with German language courses',
    entryGrades: 'Admission via GUC evaluation test plus school results — confirm requirements on the official site.',
    tests: 'GUC evaluation/admission test required; confirm English requirements on the official site.',
    acceptance: 'Competitive — fee category (A/B/C) depends on academic performance',
    tuitionIntl: 'International students pay in EUR: roughly €3,800–€5,150 per semester by faculty/category (Dentistry €5,000–€7,000) for 2026-2027 (verified, guc.edu.eg) — i.e. ~€7,600–€10,300/yr (~$8,200–$11,100 USD). Confirm current fees on the official site.',
    living: 'Cairo living costs are low by international standards — a rough estimate; confirm current figures.',
    deadline: 'Confirm application and evaluation-test dates on the official site.',
    scholarshipsHere: 'GUC offers merit-based tuition categories and some scholarships — confirm current options on the official site.',
    scholarships: [],
    sourceName: 'The German University in Cairo (official)',
    sourceUrl: 'https://www.guc.edu.eg/en/admission/undergraduate/tuition_fees/',
    verified: true,
  },
  {
    id: 'fue',
    name: 'Future University in Egypt (FUE)',
    country: 'Egypt',
    city: 'Cairo',
    flag: '🇪🇬',
    ranking: 'Private university · New Cairo',
    knownFor: ['Dentistry', 'Pharmacy', 'Engineering', 'Computer Science', 'Business'],
    language: 'English-medium instruction',
    entryGrades: 'Admission by high-school certificate (Thanaweya Amma, IB, GCSE, American Diploma) plus placement — confirm requirements on the official site.',
    tests: 'English placement test required, or an accepted English proficiency certificate — confirm the required score on the official site.',
    acceptance: 'Competitive — varies by faculty',
    tuitionIntl: 'International (non-Egyptian) undergraduate tuition 2026/2027 (verified, fue.edu.eg): Business / Economics / Computers ~$7,120/yr, Engineering ~$8,610/yr, Pharmacy ~$9,950/yr, Dentistry ~$12,350/yr. Application fee 1,600 EGP. Confirm current figures on the official site.',
    living: 'Cairo living costs are low by international standards — a rough estimate; confirm current figures.',
    deadline: 'Confirm application deadlines and intake dates on the official site.',
    scholarshipsHere: 'FUE offers merit and need-based financial support — confirm current scholarships on the official site.',
    scholarships: [],
    sourceName: 'Future University in Egypt (official)',
    sourceUrl: 'https://www.fue.edu.eg/admissions/undergraduate_applicants/tuition_fees',
    verified: true,
  },
  {
    id: 'zewail',
    name: 'University of Science and Technology at Zewail City',
    country: 'Egypt',
    city: 'Giza',
    flag: '🇪🇬',
    ranking: 'Non-profit STEM research university',
    knownFor: ['Engineering', 'Computer Science', 'Biomedical Sciences', 'Nanotechnology', 'Science'],
    language: 'English-medium instruction',
    entryGrades: 'Admission based on high-school results and the university admission criteria — confirm requirements on the official site.',
    tests: 'IELTS 5.5 or TOEFL iBT 39 minimum (per the official admission/fees page); an English exam is required before applying.',
    acceptance: 'Selective STEM admission — varies by programme',
    tuitionIntl: 'Non-Egyptian undergraduate tuition ~$250 per credit hour for 2025/2026 (per the official fees page, zewailcity.edu.eg), plus a $1,000 non-refundable enrollment deposit. Fees are charged per registered credit hour each semester — confirm your credit load and the current rate on the official site.',
    living: 'Greater Cairo living costs are low by international standards — a rough estimate; confirm current figures.',
    deadline: 'Confirm application deadlines on the official site.',
    scholarshipsHere: 'Zewail City offers merit scholarships for high-achieving STEM students — confirm current options on the official site.',
    scholarships: [],
    sourceName: 'Zewail City (official)',
    sourceUrl: 'https://www.zewailcity.edu.eg/admission-and-scholarships/undergraduate-fees',
    verified: true,
  },
]

export function getUniversitiesByCountry(countryName) {
  return UNIVERSITIES.filter(u => u.country === countryName)
}

export const UNIVERSITY_COUNTRIES = [...new Set(UNIVERSITIES.map(u => u.country))]

export const UNIVERSITY_FIELDS = [
  ...new Set(UNIVERSITIES.flatMap(u => u.knownFor)),
].sort()

/**
 * Returns university scholarships in a shape compatible with the Scholarships page.
 * Only includes entries where verified: true.
 */
export function getUniversityScholarshipsForPage() {
  return UNIVERSITIES.flatMap(u =>
    (u.scholarships || [])
      .filter(s => s.verified)
      .map((s, i) => ({
        id: `uni-${u.id}-s${i}`,
        name: s.name,
        country: u.country,
        flag: u.flag,
        fields: u.knownFor,
        amount: s.percentage,
        eligibility: s.whoQualifies,
        deadline: s.howToApply,
        deadlineMonth: s.deadlineMonth ?? 99,
        amountTier: s.amountTier ?? 2,
        level: s.level ?? 'Undergraduate',
        levelNote: '',
        sourceName: u.sourceName,
        sourceUrl: u.sourceUrl,
        verified: true,
        // attribution shown on the card
        universityName: u.name,
        universityCity: u.city,
      }))
  )
}
